### ISSUE TITLE
Doc: empty page at https://wishbone-utils.readthedocs.io/en/latest/wishbone-tool.html

### ISSUE THREAD

**Issue by tcal-x** [litex-hub/wishbone-utils#27]
I would expect it to contain a version of:
https://github.com/litex-hub/wishbone-utils/blob/master/wishbone-tool/README.md

**Comment by mithro** [comment]
Couple of issues here;
 - Symlink at https://github.com/litex-hub/wishbone-utils/blob/master/docs/wishbone-tool/index.rst goes to a non-existant file.
 - Symlinking an RST to a Markdown file isn't going to work

**Comment by mithro** [comment]
FYI - I'm not going to have time to fix this myself.

**Comment by xobs** [comment]
Thanks for the pointers on how to fix it. I think the easiest way to get it working is to add markdown support and symlink the README file.

I have something checked in now that I thought would fix it, but for whatever reason it just produces a mostly-blank page with a single "}". I couldn't build locally - `make env` didn't work for me (possibly due to https://github.com/conda/conda/issues/9948 though I don't hit that error), so it's challenging to test. I'll spend more time this afternoon getting it working.

**Comment by xobs** [comment]
Fixed by adding recommonmark support. Note that the rendering issues I was facing were due to https://github.com/readthedocs/recommonmark/issues/204
